import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./section/Header";
import Footer from "./section/Footer";

const montserrat = Montserrat({
  variable: "--font-mont",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Enforca",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-400 antialiased`}
      >
        <Header/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
